### ISSUE TITLE
Differentiate schemas by type 

### ISSUE THREAD

**Issue by aboutlo** [fastify/fluent-schema#22]
it's a large refactoring in order to move toward 1.0 

Create: 
- [ ] BaseSchema (id, title, example, required, etc.)
- [ ] StringSchema (format, pattern, etc)
- [ ] ArraySchema (items, etc)
- [ ] ObjectSchema (properties, etc)
- [ ] NumberSchema (min, max, etc)
- [ ] IntegerSchema (min, max, etc)
- [ ] BooleanSchema
- [ ] Refactor Typescript types

New syntax

```js
const schema = FluentSchema()
      .id('http://bar.com/object')
      .title('A object')
      .description('A object desc')
      .prop(
        'name',
        FluentSchema()
          .asString()
          .id('http://foo.com/string')
          .title('A string')
          .description('A string desc')
          .pattern(/.*/g)
          .format('date-time')
      )
      .valueOf()
```

it wont hint for wrong types like: 
```js
StringSchema().min(5) // Number validation keywords
```
or
```js
FluentSchema().minLength(10) // String validation keywords
```

This allows:
- better code hitting by type 
- smaller implementation files 
- Tests by type

**Comment by mcollina** [comment]
+1, I like this.

**Comment by aboutlo** [comment]
I found a possible breaking change while I'm working on the refactoring. 

```js
it('sets a type to a prop', () => {
        expect(
          FluentSchema()
            .prop('bar').asString().pattern(/.*/g)
            .prop('foo')
            .valueOf().properties.value.type
        ).toEqual('string')
      })
```

it will fail with:

`TypeError: FluentSchema(...).prop(...).asString(...).pattern(...).prop is not a function`

because `.pattern` returns a StringSchema which hasn't a prop. 
I will open a WIP as soon as I have a draft

**Comment by aboutlo** [comment]
fixed with https://github.com/fastify/fluent-schema/releases/tag/v0.6.0
