### ISSUE TITLE
Links to https://json-schema.org in the full API docs are broken

### ISSUE THREAD

**Issue by satazor** [fastify/fluent-schema#67]
## 🐛 Bug Report

Links to https://json-schema.org in the full API docs are broken.

<img width="869" alt="Screenshot 2020-05-01 at 14 51 24" src="https://user-images.githubusercontent.com/1017236/80810202-3c000180-8bbb-11ea-87ad-3a31969aac8d.png">

I believe the it should be `[reference](link)`.

## To Reproduce

Click in any link pointing to the JSON Schema reference.

## Expected behavior

Links should work.

## Your Environment

Not applicable.

**Comment by mcollina** [comment]
Would you mind to send a PR to fix? Thanks!

**Comment by satazor** [comment]
Will do!

**Comment by satazor** [comment]
@mcollina here it is: https://github.com/fastify/fluent-schema/pull/68
